site_name: PDF Plumb Documentation
site_description: PDF text extraction and analysis tool for technical documents

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan
  features:
    - content.code.annotate
    - navigation.indexes
    - search.highlight

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/docs/generate_readme.py
        - scripts/docs/generate_development.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            heading_level: 2
            filters: ["!^_"]

nav:
  - Home: index.md
  - Project README: readme.md
  - Development Guide: development.md
  - CLI Usage: cli-usage.md
  - Architecture: architecture.md
  - Status: status.md
  - Design Decisions: design-decisions.md
  - Phase History: phase-history.md
  - Guidelines:
    - Test Docstrings: test_docstring_guidelines.md
  - Design:
    - Block Grouping: design/BLOCK_GROUPING.md
    - Header Footer Detection: design/HEADER_FOOTER_DETECTION.md
    - State Machine Architecture: design/STATE_MACHINE_ARCHITECTURE.md
    - LLM Integration: design/LLM_INTEGRATION.md
    - LLM Strategy: design/LLM_STRATEGY.md
  - Analysis:
    - Token Analysis: analysis/token_analysis.md
    - LLM Strategy Evolution: analysis/llm_strategy_evolution.md
    - Performance Analysis: analysis/performance_analysis.md
  - API Reference:
    - Tests:
      - Unit Tests: api/tests/unit.md
      - Integration Tests: api/tests/integration.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences